=== Seongwonp/xml_teamProject/XML_Project/inventory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="inventory">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="currentDate"/>
        <xs:sequence maxOccurs="unbounded">
          <xs:element ref="category"/>
        </xs:sequence>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="currentDate" type="xs:string"/>

  <xs:element name="category">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="item"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
        <xs:element ref="manufacturer"/>
        <xs:element ref="expiryDate"/>
        <xs:element ref="price"/>
        <xs:element ref="quantity"/>
        <xs:element ref="remarks"/>
        <xs:element ref="image"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="id" type="xs:string"/>

  <xs:element name="name" type="xs:string"/>

  <xs:element name="manufacturer" type="xs:string"/>

  <xs:element name="expiryDate" type="xs:string"/>

  <xs:element name="price" type="xs:string"/>

  <xs:element name="quantity" type="xs:string"/>

  <xs:element name="remarks" type="xs:string"/>

  <xs:element name="image">
    <xs:complexType>
      <xs:attribute name="src" type="xs:string" use="required"/>
      <xs:attribute name="width" type="xs:string"/>
      <xs:attribute name="height" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Seongwonp/xml_teamProject/XML_Project/inventory.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="inventory_2.xsl"?>
<inventory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="inventory.xsd">
  <currentDate>20241210</currentDate>
  <!-- 커피 카테고리 -->
  <category id="1" name="커피">
    <item>
      <id>001</id>
      <name>모카골드 마일드(20)</name>
      <manufacturer>맥심</manufacturer>
      <expiryDate>20251118</expiryDate>
      <price>4500</price>
      <quantity>15</quantity>
      <remarks>
      </remarks>
      <image src="images/coffee_mix.jpg" width="100" height="100" />
    </item>
    <item>
      <id>002</id>
      <name>카페라떼(마일드)</name>
      <manufacturer>매일유업</manufacturer>
      <expiryDate>20250318</expiryDate>
      <price>1600</price>
      <quantity>40</quantity>
      <remarks>2+1</remarks>
      <image src="images/caffeelatte_mild.jpg" width="100" height="100" />
    </item>
    <item>
      <id>003</id>
      <name>스키니 라떼</name>
      <manufacturer>스타벅스</manufacturer>
      <expiryDate>20250211</expiryDate>
      <price>2600</price>
      <quantity>50</quantity>
      <remarks>할인중</remarks>
      <image src="images/starbucks_skini.jpg" width="100" height="100" />
    </item>
    <item>
      <id>004</id>
      <name>칸타타 콘트라베이스(콜드블루)</name>
      <manufacturer>롯데칠성음료</manufacturer>
      <expiryDate>20250720</expiryDate>
      <price>2500</price>
      <quantity>80</quantity>
      <remarks>
      </remarks>
      <image src="images/contrabase.jpg" width="100" height="100" />
    </item>
    <item>
      <id>005</id>
      <name>카누(아메리카노 10개입)</name>
      <manufacturer>동서</manufacturer>
      <expiryDate>20251201</expiryDate>
      <price>3100</price>
      <quantity>30</quantity>
      <remarks>할인중</remarks>
      <image src="images/kanu.jpg" width="100" height="100" />
    </item>
    <item>
      <id>006</id>
      <name>바리스타룰스 (마다가스카르 바닐라빈 라떼)</name>
      <manufacturer>매일유업</manufacturer>
      <expiryDate>20250125</expiryDate>
      <price>2700</price>
      <quantity>60</quantity>
      <remarks>2+1</remarks>
      <image src="images/barista_rules.jpg" width="100" height="100" />
    </item>
    <item>
      <id>007</id>
      <name>T.O.P(스위트 아메리카노)</name>
      <manufacturer>맥심</manufacturer>
      <expiryDate>20250812</expiryDate>
      <price>2500</price>
      <quantity>40</quantity>
      <remarks>
      </remarks>
      <image src="images/top.jpg" width="100" height="100" />
    </item>
    <item>
      <id>008</id>
      <name>아카페라 사이즈업(바닐라)</name>
      <manufacturer>빙그레</manufacturer>
      <expiryDate>20250110</expiryDate>
      <price>2400</price>
      <quantity>25</quantity>
      <remarks>1+1</remarks>
      <image src="images/size_up_vanilla.jpg" width="100" height="100" />
    </item>
    <item>
      <id>009</id>
      <name>프라푸치노(모카)</name>
      <manufacturer>스타벅스</manufacturer>
      <expiryDate>20250215</expiryDate>
      <price>2900</price>
      <quantity>70</quantity>
      <remarks>
      </remarks>
      <image src="images/starbucks_moca.jpg" width="100" height="100" />
    </item>
    <item>
      <id>010</id>
      <name>칸타타(카라멜 마끼아또)</name>
      <manufacturer>롯데칠성음료</manufacturer>
      <expiryDate>20250130</expiryDate>
      <price>2100</price>
      <quantity>45</quantity>
      <remarks>
      </remarks>
      <image src="images/cantata_caramel.jpg" width="100" height="100" />
    </item>
  </category>
  <!-- 유제품 카테고리 -->
  <category id="2" name="유제품">
    <item>
      <id>011</id>
      <name>서울우유(200ml)</name>
      <manufacturer>서울우유</manufacturer>
      <expiryDate>20241230</expiryDate>
      <price>1800</price>
      <quantity>10</quantity>
      <remarks>
      </remarks>
      <image src="images/seoul_milk_200.jpg" width="100" height="100" />
    </item>
    <item>
      <id>012</id>
      <name>초코에몽(250ml)</name>
      <manufacturer>남양</manufacturer>
      <expiryDate>20250210</expiryDate>
      <price>1300</price>
      <quantity>25</quantity>
      <remarks>2+1</remarks>
      <image src="images/chocomong.jpg" width="100" height="100" />
    </item>
    <item>
      <id>013</id>
      <name>덴마크 드링킹 요구르트(딸기)</name>
      <manufacturer>동원</manufacturer>
      <expiryDate>20241225</expiryDate>
      <price>2400</price>
      <quantity>60</quantity>
      <remarks>
      </remarks>
      <image src="images/denmark_drinking_st.jpg" width="100" height="100" />
    </item>
    <item>
      <id>014</id>
      <name>바나나맛 우유</name>
      <manufacturer>빙그레</manufacturer>
      <expiryDate>20250115</expiryDate>
      <price>1800</price>
      <quantity>70</quantity>
      <remarks>
      </remarks>
      <image src="images/bananaMilk.jpg" width="100" height="100" />
    </item>
    <item>
      <id>015</id>
      <name>딸기맛 우유</name>
      <manufacturer>빙그레</manufacturer>
      <expiryDate>20250110</expiryDate>
      <price>1800</price>
      <quantity>50</quantity>
      <remarks>
      </remarks>
      <image src="images/strawberryMilk.jpg" width="100" height="100" />
    </item>
    <item>
      <id>016</id>
      <name>매일우유(오리지널 200ml)</name>
      <manufacturer>매일유업</manufacturer>
      <expiryDate>20241214</expiryDate>
      <price>2500</price>
      <quantity>80</quantity>
      <remarks>유통기한 임박</remarks>
      <image src="images/maeilMilk.jpg" width="100" height="100" />
    </item>
    <item>
      <id>017</id>
      <name>허쉬 초콜렛드링크 (오리지널)</name>
      <manufacturer>HERSHEY'S</manufacturer>
      <expiryDate>20250102</expiryDate>
      <price>1600</price>
      <quantity>100</quantity>
      <remarks>1+1</remarks>
      <image src="images/hersheys_original.jpg" width="100" height="100" />
    </item>
    <item>
      <id>018</id>
      <name>체다치즈(3매입)</name>
      <manufacturer>서울우유</manufacturer>
      <expiryDate>20241216</expiryDate>
      <price>2000</price>
      <quantity>5</quantity>
      <remarks>유통기한 임박</remarks>
      <image src="images/chedacheese.jpg" width="100" height="100" />
    </item>
    <item>
      <id>019</id>
      <name>비요뜨</name>
      <manufacturer>서울우유</manufacturer>
      <expiryDate>20251222</expiryDate>
      <price>1500</price>
      <quantity>35</quantity>
      <remarks>2+1</remarks>
      <image src="images/Byotte.jpg" width="100" height="100" />
    </item>
    <item>
      <id>020</id>
      <name>바이요 드링킹 요거트(블루베리)</name>
      <manufacturer>매일유업</manufacturer>
      <expiryDate>20241231</expiryDate>
      <price>2300</price>
      <quantity>20</quantity>
      <remarks>
      </remarks>
      <image src="images/bio_blu.jpg" width="100" height="100" />
    </item>
  </category>
  <!-- 즉석식품 카테고리 -->
  <category id="3" name="즉석식품">
    <item>
      <id>021</id>
      <name>혜자로운 집밥(너비아니&amp;닭강정)</name>
      <manufacturer>한국데리카후레쉬</manufacturer>
      <expiryDate>20241211</expiryDate>
      <price>4900</price>
      <quantity>3</quantity>
      <remarks>유통기한 임박</remarks>
      <image src="images/jibbab_porkbelly.jpg" width="100" height="100" />
    </item>
    <item>
      <id>022</id>
      <name>햇반컵반(스펨마요덮밥)</name>
      <manufacturer>CJ제일제당</manufacturer>
      <expiryDate>20251117</expiryDate>
      <price>4500</price>
      <quantity>20</quantity>
      <remarks>2+1</remarks>
      <image src="images/spamrice.jpg" width="100" height="100" />
    </item>
    <item>
      <id>023</id>
      <name>한입쏙쏙미트볼</name>
      <manufacturer>오뚜기</manufacturer>
      <expiryDate>20250612</expiryDate>
      <price>2500</price>
      <quantity>30</quantity>
      <remarks>
      </remarks>
      <image src="images/mitball.jpg" width="100" height="100" />
    </item>
    <item>
      <id>024</id>
      <name>숯불구이맛후랑크2</name>
      <manufacturer>대림선</manufacturer>
      <expiryDate>20250608</expiryDate>
      <price>1900</price>
      <quantity>130</quantity>
      <remarks>2+1</remarks>
      <image src="images/derim_frank.jpg" width="100" height="100" />
    </item>
    <item>
      <id>025</id>
      <name>참치마요 삼각김밥</name>
      <manufacturer>푸드렐라</manufacturer>
      <expiryDate>20241213</expiryDate>
      <price>1000</price>
      <quantity>5</quantity>
      <remarks>유통기한 임박</remarks>
      <image src="images/tunamayo_trianglekim.jpg" width="100" height="100" />
    </item>
    <item>
      <id>026</id>
      <name>스펨마요김밥</name>
      <manufacturer>CJ제일제당</manufacturer>
      <expiryDate>20241125</expiryDate>
      <price>3500</price>
      <quantity>4</quantity>
      <remarks>
      </remarks>
      <image src="images/spemmayo_kim.jpg" width="100" height="100" />
    </item>
    <item>
      <id>027</id>
      <name>매콤닭강정</name>
      <manufacturer>하림</manufacturer>
      <expiryDate>20250105</expiryDate>
      <price>6000</price>
      <quantity>20</quantity>
      <remarks>할인중</remarks>
      <image src="images/harim_spicy_sauce_chicken.jpg" width="100" height="100" />
    </item>
    <item>
      <id>028</id>
      <name>자이언트 떡볶이</name>
      <manufacturer>BGF리테일</manufacturer>
      <expiryDate>20250110</expiryDate>
      <price>2200</price>
      <quantity>5</quantity>
      <remarks>
      </remarks>
      <image src="images/Giant_Tteokbokki.jpg" width="100" height="100" />
    </item>
    <item>
      <id>029</id>
      <name>오뎅한그릇</name>
      <manufacturer>CJ제일제당</manufacturer>
      <expiryDate>20250210</expiryDate>
      <price>3000</price>
      <quantity>10</quantity>
      <remarks>
      </remarks>
      <image src="images/fishcake_soup.jpg" width="100" height="100" />
    </item>
    <item>
      <id>030</id>
      <name>옛날 진한쇠고기 미역국밥</name>
      <manufacturer>오뚜기</manufacturer>
      <expiryDate>20250401</expiryDate>
      <price>4800</price>
